language: cpp
compiler: gcc

dist: trusty
sudo: required

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -y build-essential qt4-qmake
    
script:
    - qmake LibDS.pro
    - make
